### ISSUE TITLE
Won't detect GOG version of Rayman 1

### ISSUE THREAD

**Issue by icup321** [RayCarrot/Rayman-Control-Panel#1]
So I just installed Rayman 1, 2, & 3 on my laptop and tried this program out to see if it would detect all of them, and it did, except for Rayman Forever. I tried running it as admin, but that didn't work either.
EDIT: Oh, I didn't read the part that says that the game finding feature is limited to some games, I'm assuming that this is one of them.

**Comment by RayCarrot** [comment]
That's odd. It should detect the GOG versions of all games in the original trilogy. Could you check if the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GOG.com\GOGRAYMAN1" exists for you, and if so, does "path" contain the install directory?
If that key does not exist, can you check if this one exists instead: "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\GOGPACKRAYMANFOREVER_is1"? If so, I should change the key it's looking for to this one.

**Comment by RayCarrot** [comment]
I updated the program now. Let me know if it works now!

**Comment by icup321** [comment]
Ok, I tried out the new version, but unfortunately, that didn't work either. Here's the registry path, and yes "path" does contain the installation directory:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GOG.com\Games\1207658919
I also tried this program out on my main PC and it has this exact same issue.

**Comment by RayCarrot** [comment]
Can you check if these files all exist for you?
R1GOGLocation + "\game.inst"
R1GOGLocation + "\Rayman\RAYMAN.EXE"
R1GOGLocation + "\RayKit\RayKit.exe"
R1GOGLocation + "\RayFan\RayFan.exe"
R1GOGLocation + "\DosBox\DOSBox.exe"
R1GOGLocation + "\dosboxRayman.conf"
These are the files it checks for in the install directory it finds in the registry.

**Comment by icup321** [comment]
Yeah, they're all there. I think I might also mention that I'm also using the GOG Galaxy Client, so the games are installed in a different directory rather than if you download the game from the website.

**Comment by RayCarrot** [comment]
Could you give me path it's installed on?

**Comment by icup321** [comment]
C:\Program Files (x86)\GalaxyClient\Games\Rayman Forever

**Comment by RayCarrot** [comment]
Could you download this work in progress version of the next update and launch it with the argument "-error" (either through the command prompt or by creating a shortcut). This will have the program display error messages when an error occurs in the game finder. If a message appears with the name "R1 GOG", then please let me know what it says. Also reset your application data before running this file (or place it in a different directory which will automatically use a new app data file).

[Rayman Control Panel Version 3 WIP.zip](https://github.com/RayCarrot/Rayman-Control-Panel/files/1504036/Rayman.Control.Panel.Version.3.WIP.zip)

**Comment by icup321** [comment]
Ok, I got something! Here's the error:
![capture](https://user-images.githubusercontent.com/28464642/33242120-ddd8ad9c-d29d-11e7-8241-9a835eb5e859.JPG)
I also got one for the retail version of Rayman Raving Rabbids which is strange because I don't even have that version installed anymore.

**Comment by RayCarrot** [comment]
In version 2 I changed the registry key it looks for to this:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\GOGPACKRAYMANFOREVER_is1
Just to double check, that key does contain InstallLocation which has the correct directory?

As for the message, it's a generic error. At least I know where the problem is in the code (where it finds the registry key), but not why. As for Raving Rabbids, that's because the "-error" argument gives an error when it has trouble accessing the registry keys for the game, which also happens if it's not installed. This is why I don't display these errors by default.

**Comment by RayCarrot** [comment]
If the keys exist, could you check if it has read permission for users and administrators?

**Comment by icup321** [comment]
Okay, I found the InstallLocation which was located here and yes, it does have the correct directory:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\1207658919_is1
And yes, users and administrators can have read permission.

**Comment by RayCarrot** [comment]
Try this out (without the launch argument to begin with).

[Rayman Control Panel Version 3 WIP.zip](https://github.com/RayCarrot/Rayman-Control-Panel/files/1504097/Rayman.Control.Panel.Version.3.WIP.zip)

**Comment by icup321** [comment]
It worked! What was the issue?

**Comment by RayCarrot** [comment]
Your registry key ends with "1207658919_is1" while the one I had ends with "GOGPACKRAYMANFOREVER_is1". I changed it so if it doesn't find the first path it checks the second one. Probably a difference with the GOG Galaxy version as you said. Thanks for helping me find this!
